### ISSUE TITLE
Are weight files available for large models?

### ISSUE THREAD

**Issue by kadirnar** [VuongTuanKhanh/Airborne-Object-Detection-and-Tracking#3]
Have you tried it on Yolov5-M and Yolov5-X models?

**Comment by VuongTuanKhanh** [comment]
> Have you tried it on Yolov5-M and Yolov5-X models?

Actually not. But I do recommend you not to use those two models. Speed is the most important thing that need to be consider for the detection problem of this problem. So Yolov5s - the lightest and fastest version of yolov5 should be the best option.
